version: '2'
services:
    api:
        build: .
        image: cs494/api
        ports:
        - "4567:4567"
        links:
        - mysql
        - arcus
        - nbase-arc
        environment:
        - DB_HOST=mysql
        - DB_USERNAME=9muses
        - DB_PASSWORD=9muses
        - ARCUS_HOST=arcus
        - NBASE_ARC_HOST=nbase-arc
        - RACK_ENV=production
    mysql:
        build:
            context: .
            dockerfile: Dockerfile.mysql
        image: cs494/mysql
    arcus:
        image: cs494/arcus-memcached
    nbase-arc:
        image: cs494/nbase-arc
    hubblemon:
        image: cs494/hubblemon-server
        ports:
        - "8888:8888"
    ngrinder-web:
        image: ngrinder/controller:3.3
        ports:
        - "16001:16001"
        - "12000-12009:12000-12009"
        - "8999:80"
    ngrinder-agent:
        image: ngrinder/agent:3.3
        links:
        - ngrinder-web
        environment:
        - CONTROLLER_ADDR=ngrinder-web:80

